spring:
  application:
    name: iassure-incident-management
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:iassure_db}
    username: ${DB_USER:iassure_user}
    password: ${DB_PASSWORD:securepassword}
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/iassure}
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/iassure}/protocol/openid-connect/certs

flyway:
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  locations: classpath:db/migration

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
